[[nauty]]
arch = "aarch64"
git-tree-sha1 = "8b9cea6681ba444b6c58026e6561a07c2d1139c6"
os = "macos"

    [[nauty.download]]
    sha256 = "0ae406e5553590846d66897e231a5a6f0d264231a04594ccc008eefc51b9d834"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.aarch64-apple-darwin.tar.gz"
[[nauty]]
arch = "aarch64"
git-tree-sha1 = "3a7f76152da661d2cd432db338601feaca0f889b"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "62786d432fefaea3c2441838c89e33626ee62380a8f22fa2947207b85ee0e412"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.aarch64-linux-gnu.tar.gz"
[[nauty]]
arch = "aarch64"
git-tree-sha1 = "7786aaee7e637ee9c7f0d395df66cae357a79215"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "6b0ff9d31047921ac53083773c36f72c9e204d955ec0cf74d358f44e4bfa5049"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.aarch64-linux-musl.tar.gz"
[[nauty]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce20a5849b0208f9db7a8bb9c25ae93a9a342e20"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "af33c54df1535a06b2022119e93a9e03007c8cbb592e1927ff7bced53ed0508d"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.armv6l-linux-gnueabihf.tar.gz"
[[nauty]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "be948d976e7dad2cfcedd78c2bcf19529df09cbc"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "771c8798e5d7a83a7b059a76ac67ff7982c4da4dc7bcf65f1e87a9b98b46e01d"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.armv6l-linux-musleabihf.tar.gz"
[[nauty]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c38e28789d2d79f3eae67d36f4dbc55ce4f9e8b9"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "5596dc00f61d366b60a7c4569c234754fc393bda9eadf561e5e1f3a89d235135"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.armv7l-linux-gnueabihf.tar.gz"
[[nauty]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7f468e531ca99c698a8257b343beea9c31662a0a"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "0c38a0d6036bb8d9735157ffef1e118317458822991b079640d00380cc38e586"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.armv7l-linux-musleabihf.tar.gz"
[[nauty]]
arch = "i686"
git-tree-sha1 = "9fa7aee9bce5ebd581c8162f8a25d02557165e35"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "4b0c1c10382387e59cf39085a425a6f077ed665c07221d57bb450c0e380af000"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.i686-linux-gnu.tar.gz"
[[nauty]]
arch = "i686"
git-tree-sha1 = "fb43bb916508a95b15091fb3706a79784c71d7ab"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "8b6f875c0de0d005bce2dbb00c93ace63ad1e1c83ab301d27dcb72ef0394f1fd"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.i686-linux-musl.tar.gz"
[[nauty]]
arch = "powerpc64le"
git-tree-sha1 = "edd2b98416bd222afe5b670ddeadc6eb4e27a350"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "66668f212bef40aa7f3b9b3c9390db8665d768855f5df1b767d2fbbe62094593"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.powerpc64le-linux-gnu.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "629e91b303e1554cb322bbe1a85233a7ab21693a"
os = "macos"

    [[nauty.download]]
    sha256 = "26230b9aee54c94abd33f46c36aa589cd442e65a5f7639c46892702daed0ae76"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.x86_64-apple-darwin.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "cced79d524c8a718194570890cdd7964bc77f09a"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "33fae4a2fc3f751ba6941860f4fd9beaa3f4fd36b2e2accac780e30a604b867a"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.x86_64-linux-gnu.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "83f66b862d17e0fd3cc8ce75e37891c1e2e1fcf9"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "022a9d5ebfead7d60648e522138441e429314a606d78e06436c6b867051f50da"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.x86_64-linux-musl.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "b348e04dfb5bc91ce5782b64132322f6174c6934"
os = "freebsd"

    [[nauty.download]]
    sha256 = "29be7996bdcd0f407f7821974e5b7e79b6a235c049dd601e5fc83f5fb49bb9ec"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.13+0/nauty.v2.6.13.x86_64-unknown-freebsd.tar.gz"
