[[nauty]]
arch = "aarch64"
git-tree-sha1 = "314c67a60293a5ceff29916f0fc38083d5bcb643"
os = "macos"

    [[nauty.download]]
    sha256 = "255097fdf6313394c90043febd2dd39dc61f779957813f539d035457a27d1086"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.aarch64-apple-darwin.tar.gz"
[[nauty]]
arch = "aarch64"
git-tree-sha1 = "7d15c50ce73439b0d662874755ca3882c26e17b5"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "ab775a5301bb84146d2cd672c911a537d9885633a689859f4f6f59eca74ef1d6"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.aarch64-linux-gnu.tar.gz"
[[nauty]]
arch = "aarch64"
git-tree-sha1 = "7c95f85581acb156a576ce97fa5d0e9e25926ac3"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "20a4e59e01db32e07375da18b4b23e63a1ee53cb26e8736a70573820225614ce"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.aarch64-linux-musl.tar.gz"
[[nauty]]
arch = "aarch64"
git-tree-sha1 = "301706058ef36fb9b049c8408be49e5947e9b63b"
os = "freebsd"

    [[nauty.download]]
    sha256 = "8532e17621f8d538e829ef75b255b31138621fa9b5167cd281eeab8e3cd4bfea"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.aarch64-unknown-freebsd.tar.gz"
[[nauty]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0ab01edd9961a6facf4b4574a8ae146212001e55"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "d8501cc82e8669aefafbccee296ca4f5a07b3c28d5842006caf7cd51fe7813bd"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.armv6l-linux-gnueabihf.tar.gz"
[[nauty]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "699c2e2e9f9764e78bec18d8efe2562ee48509b9"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "e1557b6f98688097bd126dc618c7666b72e171f6d678aaf51246be61c7100d38"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.armv6l-linux-musleabihf.tar.gz"
[[nauty]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9202ced5a5c6c9ea6f158fd83dfb7fc130ac764f"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "9b6534d365685d405b2c5b3d3dc34a2de57a8783e826770a298864c5bb4e2ef3"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.armv7l-linux-gnueabihf.tar.gz"
[[nauty]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cdf9380edccac9ef409bec193476323412718812"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "e800fa2722339164ac4686390ec8403215cbcede3b00ffe6a87f8689658bacd7"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.armv7l-linux-musleabihf.tar.gz"
[[nauty]]
arch = "i686"
git-tree-sha1 = "1badf705e8669b26860397f99eaa8b1eb290458a"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "f4f84b9e074a3abbea14431126c673ae9274d9ea5bddb2680745a910f5fd8b6a"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.i686-linux-gnu.tar.gz"
[[nauty]]
arch = "i686"
git-tree-sha1 = "559ee8dd6030b3e26c5660f9dd62c8f47ead7d14"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "b66474382e1b470ebacec34f392635167a83032ba9f2fea59981d70a83f083df"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.i686-linux-musl.tar.gz"
[[nauty]]
arch = "powerpc64le"
git-tree-sha1 = "1ac8e8b67a6a676a8b6209e93156818790231966"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "0c2695953152882aaff2471c6522b9afadc60aa0b24de9018172abbd4f8e497f"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.powerpc64le-linux-gnu.tar.gz"
[[nauty]]
arch = "riscv64"
git-tree-sha1 = "3ad6fdb6cece9483a192cc45321dd9bc5de7ca8d"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "7f9a9ef6d4e15be4bf9b8095f309a0aaadca6e3381e5d00f62cd27c75297ef6b"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.riscv64-linux-gnu.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "3f59eacd1535a6ba12a8303fedcea9f7259173af"
os = "macos"

    [[nauty.download]]
    sha256 = "508553145c49be43efe6739d7fe08f5b083dd03b06b7a31b15cc10a4cd6c4adb"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.x86_64-apple-darwin.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "6de1c7163952ec56b74ddb020aae9cb6e933e58c"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "d93719295c882116d364e70b2d4fb60b93be1245b1bb7529595af833e2c2c772"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.x86_64-linux-gnu.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "3898ee3aabe962c854c76b61fced4a4780eb92ca"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "edc1531303451525518304dafb67c4088972f527eb6bd52fc15687eb981ddd4f"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.x86_64-linux-musl.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "8718fd31613cc5ca60e6616e219cc414172efe2c"
os = "freebsd"

    [[nauty.download]]
    sha256 = "ed5ce7608588067b78fbba942ca7a0bb45f1b79e74e2b4be89b7d1df99558175"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.8.10+0/nauty.v2.8.10.x86_64-unknown-freebsd.tar.gz"
