[[nauty]]
arch = "i686"
git-tree-sha1 = "b0ec9a33d26dad7061ce5864347a4c2464d4ed29"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "8dd5d3ad6eb0c38a2feaebf43133cf49a66cc2cb609e8d186a1ed21621c92dc3"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.i686-linux-musl.tar.gz"
[[nauty]]
arch = "aarch64"
git-tree-sha1 = "56912b5aab368ec6b38ef85db5609d9e1d7766e2"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "dcdcc83713ff65266404573123e9fde7f9182cfc70bfa4e7a6ce0b1392793bd0"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.aarch64-linux-musl.tar.gz"
[[nauty]]
arch = "armv7l"
git-tree-sha1 = "e2175160dc7d885fcf6b13e1545239958b452477"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "a4de2b994f9d71998c1acc7835f6cfdf2a34eedc4a3b4fc3901974918ec10961"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.armv7l-linux-gnueabihf.tar.gz"
[[nauty]]
arch = "armv7l"
git-tree-sha1 = "77a0d80d41644955099c184a31d7808c960b84d7"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "a7fafd55f31edf7f517f095ea1eb3dca272a080f345f1e9849b5d5735da3d8fa"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.armv7l-linux-musleabihf.tar.gz"
[[nauty]]
arch = "i686"
git-tree-sha1 = "282b91227ca0fa97abb192c2de77b628301a4bca"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "cedc51c75b6a2cb3baae4f07068116f26671db0b5699a21a210d35de73262c39"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.i686-linux-gnu.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "73247ee194631a1a0100b72573cea7adadb6d3bd"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "c1aa848aad48754d324f0f660feed3c493efeff4fbd585f84b7aed3ef4f4f0d8"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.x86_64-linux-gnu.tar.gz"
[[nauty]]
arch = "powerpc64le"
git-tree-sha1 = "eee545c7d0481d854d36038ca66ec3c64f403fda"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "c1324c66c141b9dbf31d99cec78dbafb4ea4e8bcf396d98e009f70e616410ab7"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.powerpc64le-linux-gnu.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "120a90ae0a1924bd00562a0d6e9e296619640b5c"
os = "macos"

    [[nauty.download]]
    sha256 = "4464b165292b04c8df69527456365907e7af474dfde9e312ffc750d09cb2c3d0"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.x86_64-apple-darwin14.tar.gz"
[[nauty]]
arch = "aarch64"
git-tree-sha1 = "5a36df27f25d27aa4dd6472e64b4e0013f939520"
libc = "glibc"
os = "linux"

    [[nauty.download]]
    sha256 = "650a9412d6c94fa79b737e24c10ec215d0366b33df5d84165f9b7ac6fb18f9e8"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.aarch64-linux-gnu.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "2883051957a7a096a167ea9418c5bc07f167cf49"
os = "freebsd"

    [[nauty.download]]
    sha256 = "dbad1885eaebd0b364a9d499c1a2a48ed587459396be991ba5ffc76a0f1becf4"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.x86_64-unknown-freebsd11.1.tar.gz"
[[nauty]]
arch = "x86_64"
git-tree-sha1 = "24ef2a9a8c45e540afbe3e2999d256704aabf8a6"
libc = "musl"
os = "linux"

    [[nauty.download]]
    sha256 = "7f1c1e5a162aedc4e91d456b8889f09ddeb5d613c8bbcea11602583fff75f1c9"
    url = "https://github.com/JuliaBinaryWrappers/nauty_jll.jl/releases/download/nauty-v2.6.12+0/nauty.v2.6.12.x86_64-linux-musl.tar.gz"
