# Autogenerated wrapper script for nauty_jll for armv6l-linux-musleabihf
export NRswitchg, addedgeg, amtog, biplabg, blisstog, catg, checks6, complg, converseg, copyg, countg, cubhamg, deledgeg, delptg, directg, dreadnaut, dretodot, dretog, genbg, genbgL, geng, genquarticg, genrang, genspecialg, gentourng, gentreeg, hamheuristic, labelg, libnauty, libnautyA1, libnautyL0, libnautyL1, libnautyS0, libnautyS1, libnautyW0, libnautyW1, linegraphg, listg, multig, newedgeg, pickg, planarg, ranlabg, shortg, showg, subdivideg, sumlines, twohamg, vcolg, watercluster2

using GMP_jll
JLLWrappers.@generate_wrapper_header("nauty")
JLLWrappers.@declare_executable_product(NRswitchg)
JLLWrappers.@declare_executable_product(addedgeg)
JLLWrappers.@declare_executable_product(amtog)
JLLWrappers.@declare_executable_product(biplabg)
JLLWrappers.@declare_executable_product(blisstog)
JLLWrappers.@declare_executable_product(catg)
JLLWrappers.@declare_executable_product(checks6)
JLLWrappers.@declare_executable_product(complg)
JLLWrappers.@declare_executable_product(converseg)
JLLWrappers.@declare_executable_product(copyg)
JLLWrappers.@declare_executable_product(countg)
JLLWrappers.@declare_executable_product(cubhamg)
JLLWrappers.@declare_executable_product(deledgeg)
JLLWrappers.@declare_executable_product(delptg)
JLLWrappers.@declare_executable_product(directg)
JLLWrappers.@declare_executable_product(dreadnaut)
JLLWrappers.@declare_executable_product(dretodot)
JLLWrappers.@declare_executable_product(dretog)
JLLWrappers.@declare_executable_product(genbg)
JLLWrappers.@declare_executable_product(genbgL)
JLLWrappers.@declare_executable_product(geng)
JLLWrappers.@declare_executable_product(genquarticg)
JLLWrappers.@declare_executable_product(genrang)
JLLWrappers.@declare_executable_product(genspecialg)
JLLWrappers.@declare_executable_product(gentourng)
JLLWrappers.@declare_executable_product(gentreeg)
JLLWrappers.@declare_executable_product(hamheuristic)
JLLWrappers.@declare_executable_product(labelg)
JLLWrappers.@declare_library_product(libnauty, "libnauty.so.2")
JLLWrappers.@declare_library_product(libnautyA1, "libnautyA1.so.2")
JLLWrappers.@declare_library_product(libnautyL0, "libnautyL0.so.2")
JLLWrappers.@declare_library_product(libnautyL1, "libnautyL1.so.2")
JLLWrappers.@declare_library_product(libnautyS0, "libnautyS0.so.2")
JLLWrappers.@declare_library_product(libnautyS1, "libnautyS1.so.2")
JLLWrappers.@declare_library_product(libnautyW0, "libnautyW0.so.2")
JLLWrappers.@declare_library_product(libnautyW1, "libnautyW1.so.2")
JLLWrappers.@declare_executable_product(linegraphg)
JLLWrappers.@declare_executable_product(listg)
JLLWrappers.@declare_executable_product(multig)
JLLWrappers.@declare_executable_product(newedgeg)
JLLWrappers.@declare_executable_product(pickg)
JLLWrappers.@declare_executable_product(planarg)
JLLWrappers.@declare_executable_product(ranlabg)
JLLWrappers.@declare_executable_product(shortg)
JLLWrappers.@declare_executable_product(showg)
JLLWrappers.@declare_executable_product(subdivideg)
JLLWrappers.@declare_executable_product(sumlines)
JLLWrappers.@declare_executable_product(twohamg)
JLLWrappers.@declare_executable_product(vcolg)
JLLWrappers.@declare_executable_product(watercluster2)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_executable_product(
        NRswitchg,
        "bin/NRswitchg",
    )

    JLLWrappers.@init_executable_product(
        addedgeg,
        "bin/addedgeg",
    )

    JLLWrappers.@init_executable_product(
        amtog,
        "bin/amtog",
    )

    JLLWrappers.@init_executable_product(
        biplabg,
        "bin/biplabg",
    )

    JLLWrappers.@init_executable_product(
        blisstog,
        "bin/blisstog",
    )

    JLLWrappers.@init_executable_product(
        catg,
        "bin/catg",
    )

    JLLWrappers.@init_executable_product(
        checks6,
        "bin/checks6",
    )

    JLLWrappers.@init_executable_product(
        complg,
        "bin/complg",
    )

    JLLWrappers.@init_executable_product(
        converseg,
        "bin/converseg",
    )

    JLLWrappers.@init_executable_product(
        copyg,
        "bin/copyg",
    )

    JLLWrappers.@init_executable_product(
        countg,
        "bin/countg",
    )

    JLLWrappers.@init_executable_product(
        cubhamg,
        "bin/cubhamg",
    )

    JLLWrappers.@init_executable_product(
        deledgeg,
        "bin/deledgeg",
    )

    JLLWrappers.@init_executable_product(
        delptg,
        "bin/delptg",
    )

    JLLWrappers.@init_executable_product(
        directg,
        "bin/directg",
    )

    JLLWrappers.@init_executable_product(
        dreadnaut,
        "bin/dreadnaut",
    )

    JLLWrappers.@init_executable_product(
        dretodot,
        "bin/dretodot",
    )

    JLLWrappers.@init_executable_product(
        dretog,
        "bin/dretog",
    )

    JLLWrappers.@init_executable_product(
        genbg,
        "bin/genbg",
    )

    JLLWrappers.@init_executable_product(
        genbgL,
        "bin/genbgL",
    )

    JLLWrappers.@init_executable_product(
        geng,
        "bin/geng",
    )

    JLLWrappers.@init_executable_product(
        genquarticg,
        "bin/genquarticg",
    )

    JLLWrappers.@init_executable_product(
        genrang,
        "bin/genrang",
    )

    JLLWrappers.@init_executable_product(
        genspecialg,
        "bin/genspecialg",
    )

    JLLWrappers.@init_executable_product(
        gentourng,
        "bin/gentourng",
    )

    JLLWrappers.@init_executable_product(
        gentreeg,
        "bin/gentreeg",
    )

    JLLWrappers.@init_executable_product(
        hamheuristic,
        "bin/hamheuristic",
    )

    JLLWrappers.@init_executable_product(
        labelg,
        "bin/labelg",
    )

    JLLWrappers.@init_library_product(
        libnauty,
        "lib/libnauty.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnautyA1,
        "lib/libnautyA1.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnautyL0,
        "lib/libnautyL0.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnautyL1,
        "lib/libnautyL1.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnautyS0,
        "lib/libnautyS0.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnautyS1,
        "lib/libnautyS1.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnautyW0,
        "lib/libnautyW0.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnautyW1,
        "lib/libnautyW1.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        linegraphg,
        "bin/linegraphg",
    )

    JLLWrappers.@init_executable_product(
        listg,
        "bin/listg",
    )

    JLLWrappers.@init_executable_product(
        multig,
        "bin/multig",
    )

    JLLWrappers.@init_executable_product(
        newedgeg,
        "bin/newedgeg",
    )

    JLLWrappers.@init_executable_product(
        pickg,
        "bin/pickg",
    )

    JLLWrappers.@init_executable_product(
        planarg,
        "bin/planarg",
    )

    JLLWrappers.@init_executable_product(
        ranlabg,
        "bin/ranlabg",
    )

    JLLWrappers.@init_executable_product(
        shortg,
        "bin/shortg",
    )

    JLLWrappers.@init_executable_product(
        showg,
        "bin/showg",
    )

    JLLWrappers.@init_executable_product(
        subdivideg,
        "bin/subdivideg",
    )

    JLLWrappers.@init_executable_product(
        sumlines,
        "bin/sumlines",
    )

    JLLWrappers.@init_executable_product(
        twohamg,
        "bin/twohamg",
    )

    JLLWrappers.@init_executable_product(
        vcolg,
        "bin/vcolg",
    )

    JLLWrappers.@init_executable_product(
        watercluster2,
        "bin/watercluster2",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
